sudo: required

language: generic

services:
  - docker  
  
before_install:
  - docker build -t jbmcnamara211/docker-react -f dockerfile.dev .
   
script:
  - docker run -e CI=true jbmcnamara211/docker-react npm run test 
  
deploy:
  provider: elasticbeanstalk
  region: "us-west-1"
  
  app: "dockerreact"
  env: "Dockerreact-env"
  
  bucket_name: "aws:elasticbeanstalk:us-west-1:474486899886:application/docker-react"
  bucket_path: "docker-react"
  on:
    branch: master
access_key_id: $AWS_ACCESS_KEY 
secret_access_key:
  secure: "$AWS_SECRET_KEY"	
  
