sudo: required

language: generic

services:
  - docker  
  
before_install:
  - docker build -t jbmcnamara211/docker-react -f dockerfile.dev .
   
script:
  - docker run -e CI=true jbmcnamara211/docker-react npm run test 
  
deploy:
  provider: elasticbeanstalk
  region: "us-west-1"
  
  app: "docker"
  env: "Docker-env"
  
  bucket_name: "elasticbeanstalk-us-west-1-474486899886"
  bucket_path: "docker"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
    	
    
  
